### ISSUE TITLE
Bug in server.ts prevents this from running

### ISSUE THREAD

**Issue by osseonews** [lane711/sonicjs#215]
```
app.get("/public/*", async (ctx) => {
  return await ctx.env.ASSETS.fetch(ctx.req.raw);
});
```
line 44 in server.ts throws an error. ASSETS is undefined. What is this ENV supposed to be and where? Also, get an error: "Property 'fetch' does not exist on type 'string'

Not sure if this error is what is causing the admin to not work at all, i.e. we can't create new records in the tables we have set up or edit anything else.

**Comment by lane711** [comment]
Are you able to access /status when running locally? If so, what is the output? 

Did you create your app with `npx create-sonicjs-app` ?

**Comment by osseonews** [comment]
No, we couldn't use npx create-sonicjs-app. Just kept throwing errors.

**Comment by lane711** [comment]
Sorry to hear that. If the npx script isn't working for you, you should be able to:

1. Clone the repo
2. `npm install`
3. rename `/wrangler.example.toml` to `/wrangler.toml`
4. fill in the values of wrangler.toml per the instructions included in the same file as comments.
5. `npm run dev`

Please post any errors that you are getting with this process. I'd like to get them fixed. 

Please also share OS, node version, etc so that I can attempt to replicate.

**Comment by lane711** [comment]
Here is what your status page should look like. Note that `ASSETS` are included in the env from Hono js.

<img width="783" alt="Screenshot 2023-11-08 at 7 17 16 AM" src="https://github.com/lane711/sonicjs/assets/4350219/8628a6a1-c197-48e2-9db3-d0a3fe9fa9ca">

**Comment by osseonews** [comment]
I'll try to do everything again. But, also, I still get this error, raised by someone else in another issue: "Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises"

**Comment by osseonews** [comment]
OK, I got it working now locally after cloning it again.

**Comment by lane711** [comment]
SonicJs has been completely rewritten on top of Astro, so this issue should no longer be present.
